---
title: "climate_data"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

- Prepara climate data 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

```{r, eval=FALSE}
raw <- read_csv("/Users/ajpelu/Downloads/cn_PSN07_166.csv")
variables <- read.csv("/Users/ajpelu/Downloads/cn_variables.tsv", sep="\t")
dat <- read_csv("/Users/ajpelu/Downloads/PSN07_diario_2021.csv") %>% clean_names() 

dat2021 <- dat %>% 
  mutate(date = as.Date(format(as.Date(fecha, format = "%d/%m/%Y"),
                        "%Y-%m-%d"))) %>% 
           dplyr::select(
    date, 
    tmed = temperatura_media_o_c, 
    tmax = temperatura_maxima_o_c, 
    tmin = temperatura_minimo_o_c, 
    prec = lluvia_acumulada_mm) 


prec_dialy <- raw %>% 
  filter(variable_id == 49) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(date = as.Date(lubridate::ymd_hms(time), format = "%Y-%m-%d")) %>%
  group_by(date) %>% 
  summarise(prec = sum(value))

prec_dialy <- prec_dialy %>% 
  bind_rows(
    (dat2021 %>% 
       dplyr::select(date, prec))
  )

temp_dialy <- raw %>% 
  filter(variable_id == 108) %>%
  mutate(value = as.numeric(value)) %>% 
  mutate(date = as.Date(lubridate::ymd_hms(time), format = "%Y-%m-%d")) %>%
  group_by(date) %>% 
  summarise(tmin = min(value),
            tmax = max(value),
            tmed = mean(value))


temp_dialy <- temp_dialy %>% 
  bind_rows(
    (dat2021 %>% 
       dplyr::select(date, tmin, tmax, tmed))
  )

climate <- prec_dialy %>% 
  inner_join(temp_dialy)

write_csv(climate, "data/climate_psn07_canar.csv")
```


```{r, message=FALSE}
climate <- read_csv("data/climate_psn07_canar.csv")
```

# Precipitation
- Data from PSN_07 (Estación Meteorológica Cáñar)

```{r}
prec_monthly <- climate %>%
  dplyr::select(date, prec) %>% 
  mutate(date_ym = format(date, "%Y-%m")) %>% 
  group_by(date_ym) %>% 
  summarise(monthly_prec = sum(prec)) %>% 
  mutate(date = lubridate::parse_date_time(date_ym, "ym", tz = "CET"))
  
prec_monthly %>% 
  ggplot(aes(x=date, y=monthly_prec)) +
  geom_bar(stat = "identity") 
```

```{r}
date_samplings <- as.Date(c("2008-04-29",
                            "2011-04-26",
                            "2014-05-07"),
                            format="%Y-%m-%d")
```

## Get 3-6 month previously to sampling: 
  
```{r}
pre2008 <- climate %>% 
  filter(date >= as.Date("2008-01-01", format="%Y-%m-%d")) %>% 
  filter(date < as.Date("2008-04-29", format="%Y-%m-%d")) 

pre2011 <- climate %>%
  filter(date >= as.Date("2011-01-01", format="%Y-%m-%d")) %>% 
  filter(date < as.Date("2011-04-26", format="%Y-%m-%d")) 
  
pre2014 <- climate %>%
  filter(date >= as.Date("2014-01-01", format="%Y-%m-%d")) %>% 
  filter(date < as.Date("2014-05-07", format="%Y-%m-%d"))                     

pre_cum <- 
  bind_rows(
    pre2008, pre2011, pre2014) %>% 
  mutate(year = lubridate::year(date), 
         doy = lubridate::yday(date))

pre_cum %>% 
  ggplot(aes(x=doy, y=prec)) +
  geom_bar(stat = "identity") +
  facet_wrap(~year, ncol = 1) +
  ylab("Precipitation (mm)") + 
  xlab("Day of Year") +
  theme_bw() + 
  theme(
    panel.grid = element_blank(),
    # panel.grid.major.x = element_blank(),
    strip.background = element_rect(fill=NA), 
    strip.text = element_text(face="italic")
  ) 
  
```

## Cummulative precipitation
```{r}
prec_cum_mean <- climate %>% 
  mutate(doy = lubridate::yday(date), 
         year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  mutate(cum = cumsum(prec)) %>% 
  dplyr::select(doy, cum, year) %>% 
  group_by(doy) %>% 
  summarise(mean = mean(cum, na.rm=TRUE),
          sd = sd(cum, na.rm = TRUE),
          se = sd/sqrt(length(cum))) %>% 
  rename(cum = mean) %>% 
  mutate(year = as.character("2008-2021"))

prec_cum_line <- 
  pre_cum %>% 
  mutate(year = as.factor(year)) %>% 
  group_by(year) %>% 
  mutate(cum = cumsum(prec)) %>% 
  dplyr::select(doy, year, cum) %>% 
  mutate(year = as.character(year)) %>% 
  relocate(year, .after = doy)

points <- prec_cum_line %>% 
 group_by(year) %>% 
  filter(doy ==  max(doy))
prec_cum_line_avg <- 
  bind_rows(prec_cum_line, prec_cum_mean) %>%
  filter(doy < 127) %>% 
  rowwise() %>% 
  mutate(days_to_sampling = case_when(
    year == "2008" ~ (doy - 119), 
    year == "2011" ~ (doy - 115), 
    year == "2014" ~ (doy - 126), 
    year == "2008-2021" ~ (doy - 126))) 
    

prec_cum_line_avg %>% 
  ggplot(aes(x=doy, y=cum, col=as.factor(year))) +
  geom_ribbon(aes(ymin = cum - se, ymax = cum + se), 
              fill="gray", alpha = .1, linetype = 2, 
              show.legend = FALSE) + 
  geom_line() +
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  ylab("Cummulative Rainfall (mm)") +
  xlab("Day of year") + 
  scale_color_manual(values=c("lightblue", "gray", "black", "orange"), 
                     name = "year") +
  geom_point(data = points, 
             aes(x=doy, y=cum), 
             size = 3) 
```


```{r, eval=FALSE, echo=FALSE}
prec_cum_line <- 
  pre_cum %>% 
  group_by(year) %>% 
  mutate(cum = cumsum(prec))

points <- prec_cum_line %>% 
 group_by(year) %>% 
  filter(doy ==  max(doy))

prec_cum_line %>% 
  ggplot(aes(x=doy, y=cum, col=as.factor(year))) +
  geom_line() +
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  ylab("Cummulative Rainfall (mm)") +
  xlab("Day of year") + 
  scale_color_manual(values=c("lightblue", "black", "orange"), 
                     name = "year") +
  geom_point(data = points, 
             aes(x=doy, y=cum), 
             size = 3)
  
```

```{r}
col <- c("2008" = "lightblue",
         "2011" = "black",
         "2014" = "orange")

points %>% 
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(x=year, y=cum, fill=year)) +
  geom_bar(stat="identity") +
    scale_fill_manual(values = col, name = "year") +
  ylab("Cummulative Rainfall (mm)") +
  xlab("Year") +
    theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) 
```


# Temperature 
```{r}

t2008 <- pre_cum %>% 
  filter(year == 2008) %>% 
  filter(date >= as.Date("2008-03-29", format="%Y-%m-%d")) %>% 
  arrange(desc(doy)) %>% 
  mutate(d = -seq.int(nrow(.)))

t2011 <- pre_cum %>% 
  filter(year == 2011) %>% 
  filter(date >= as.Date("2011-03-26", format="%Y-%m-%d")) %>% 
  arrange(desc(doy)) %>% 
  mutate(d = -seq.int(nrow(.)))


t2014 <- pre_cum %>% 
  filter(year == 2014) %>% 
  filter(date >= as.Date("2014-04-06", format="%Y-%m-%d"))%>% 
  arrange(desc(doy)) %>% 
  mutate(d = -seq.int(nrow(.))) 

temp <- bind_rows(t2008,t2011,t2014) %>% dplyr::select(-prec)

```

```{r}
temp %>% 
  mutate(year = as.factor(year)) %>% 
  ggplot(aes(x=d, y=tmed, colour=year)) +
  geom_ribbon(aes(ymin = tmin, ymax=tmax, fill=year), 
              colour=NA, alpha=.2) +
  geom_line() +
  scale_fill_manual(values = col, name = "year") +
  scale_colour_manual(values = col, name = "year") +
  ylab("Temperature (º)") +
  xlab("Previous days") +
    theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) 
```

```{r}
temp %>% 
  dplyr::select(tmin, tmax, tmed, year) %>% 
  group_by(year) %>% 
  summarise(across(tmin:tmed, list(
    mean = mean,
    sd = sd))) %>% 
  mutate_at(2:7, list(~round(., 2))) %>% 
  unite("tmean", starts_with("tmed"), sep = " ± ") %>% 
  unite("tmin", starts_with("tmin"), sep = " ± ") %>% 
  unite("tmax", starts_with("tmax"), sep = " ± ") %>% 
  kableExtra::kbl() %>% 
  kable_styling()
```


