---
title: "Explore NDVI"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

### MODIS NDVI 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
```


```{r}
raw_modis <- read_csv("data/lanjaron_modis_iv_plots.csv") |> 
  mutate(date = lubridate::ymd(
    as.Date(gsub('_[^_]*$', '', `system:index`), format='%Y_%m_%d'))) |> 
  mutate(evi = EVI/10000, 
         ndvi = NDVI/10000) |> 
  mutate(treatment = ifelse(str_detect(name, pattern = 'N'), "unburned", "burned")) |> 
  dplyr::select(
    date, plot=name, treatment, ndvi, evi)


iv_modis <- raw_modis |>
  mutate(date_ym = format(date, "%Y-%m")) |> 
  group_by(date_ym, plot, treatment) |> 
    summarise(mean = mean(ndvi, na.rm = TRUE), 
            sd = sd(ndvi, na.rm = TRUE), 
            se = sd/sqrt(length(ndvi)),
            cv = sd/mean*100,
            median = median(ndvi, na.rm=TRUE)) |> 
  mutate(date = lubridate::parse_date_time(date_ym, "ym", tz = "CET")) |> 
  ungroup()


iv_modis_y <- raw_modis |>
  mutate(date_ym = format(date, "%Y")) |> 
  group_by(date_ym, plot, treatment) |> 
    summarise(mean = mean(ndvi, na.rm = TRUE), 
            sd = sd(ndvi, na.rm = TRUE), 
            se = sd/sqrt(length(ndvi)),
            cv = sd/mean*100,
            median = median(ndvi, na.rm=TRUE)) |> 
  mutate(date = lubridate::parse_date_time(date_ym, "y", tz = "CET")) |> 
  ungroup()

```


```{r}
date_incendio <- as.Date("2005-09-22", format="%Y-%m-%d")
date_samplings <- as.Date(c("2008-04-29",
                            "2011-04-26",
                            "2014-05-07"),
                            format="%Y-%m-%d")
```

```{r}
cols <- c("LJN1" = "#00441b",
          "LJN2" = "#74c476",
          "LJN3" = "#02818a",
          "LJQ2" = "#800026",
          "LJQ1" = "#bf812d",
          "LJQ3" = "#543005")

cols2 <- c("LJN1" = "#74c476",
          "LJN2" = "#74c476",
          "LJN3" = "#74c476",
          "LJQ2" = "#543005",
          "LJQ1" = "#543005",
          "LJQ3" = "#543005")



iv_modis_plot <- iv_modis_y |> 
  ggplot(aes(x=date, y=mean)) + 
  geom_ribbon(aes(ymin = (mean - se), ymax=(mean+se), fill=plot), 
              colour=NA, alpha=.2) +
  geom_line(aes(linetype = plot, colour = plot)) +
  scale_fill_manual(values=cols2, name="") +
  scale_colour_manual(values=cols2, name="") +
  theme_bw() +
  ylab("MODIS NDVI annual mean") + xlab("") +
  theme(
    panel.grid = element_blank(),
    # panel.grid.major.x = element_blank(),
    strip.background = element_rect(fill=NA), 
    strip.text = element_text(face="italic")
  ) 

iv_modis_plot
```


```{r}
ggsave(iv_modis_plot, 
       filename= here::here("output/ndvi_modis.png"), 
       device = "png", height = 10, width = 18, unit = "cm", dpi=150)
```



